// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SPASMART.Data;

#nullable disable

namespace SPASMART.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SPASMART.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaChiTietHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaChiTietHoaDon"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("MaChiTietHoaDon");

                    b.HasIndex("MaDichVu");

                    b.HasIndex("MaHoaDon");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("SPASMART.Models.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("MaChiTietPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaChiTietPhieuNhap"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("MaPhieuNhap")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("MaChiTietPhieuNhap");

                    b.HasIndex("MaPhieuNhap");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("SPASMART.Models.DichVu", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaDichVu"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaDichVu");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("SPASMART.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("MaLichHen")
                        .HasColumnType("int");

                    b.Property<int?>("MaVoucher")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaLichHen")
                        .IsUnique();

                    b.HasIndex("MaVoucher")
                        .IsUnique();

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("SPASMART.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("EmailKhach")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HoTenKhach")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SoDienThoaiKhach")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("SPASMART.Models.LichHen", b =>
                {
                    b.Property<int>("MaLichHen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaLichHen"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("GioHen")
                        .HasColumnType("time(6)");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayHen")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaLichHen");

                    b.HasIndex("MaDichVu");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("LichHens");
                });

            modelBuilder.Entity("SPASMART.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("SPASMART.Models.PhieuNhap", b =>
                {
                    b.Property<int>("MaPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaPhieuNhap"));

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("MaPhieuNhap");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("PhieuNhaps");
                });

            modelBuilder.Entity("SPASMART.Models.SanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaSanPham"));

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("HanSuDung")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LoaiSanPham")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaSanPham");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("SPASMART.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("SPASMART.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<string>("HinhThucThanhToan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaHoaDon");

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("SPASMART.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTros");
                });

            modelBuilder.Entity("SPASMART.Models.Voucher", b =>
                {
                    b.Property<int>("MaVoucher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaVoucher"));

                    b.Property<decimal>("GiaTriGiam")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TenVoucher")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaVoucher");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("SPASMART.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("SPASMART.Models.DichVu", "DichVu")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPASMART.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("SPASMART.Models.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("SPASMART.Models.PhieuNhap", "PhieuNhap")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPASMART.Models.SanPham", "SanPham")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuNhap");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("SPASMART.Models.HoaDon", b =>
                {
                    b.HasOne("SPASMART.Models.LichHen", "LichHen")
                        .WithOne("HoaDon")
                        .HasForeignKey("SPASMART.Models.HoaDon", "MaLichHen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPASMART.Models.Voucher", "Voucher")
                        .WithOne("HoaDon")
                        .HasForeignKey("SPASMART.Models.HoaDon", "MaVoucher");

                    b.Navigation("LichHen");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("SPASMART.Models.KhachHang", b =>
                {
                    b.HasOne("SPASMART.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("SPASMART.Models.KhachHang", "MaTaiKhoan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("SPASMART.Models.LichHen", b =>
                {
                    b.HasOne("SPASMART.Models.DichVu", "DichVu")
                        .WithMany("LichHens")
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPASMART.Models.KhachHang", "KhachHang")
                        .WithMany("LichHens")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPASMART.Models.NhanVien", "NhanVien")
                        .WithMany("LichHens")
                        .HasForeignKey("MaNhanVien");

                    b.Navigation("DichVu");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("SPASMART.Models.NhanVien", b =>
                {
                    b.HasOne("SPASMART.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("NhanVien")
                        .HasForeignKey("SPASMART.Models.NhanVien", "MaTaiKhoan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("SPASMART.Models.PhieuNhap", b =>
                {
                    b.HasOne("SPASMART.Models.NhanVien", "NhanVien")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("SPASMART.Models.TaiKhoan", b =>
                {
                    b.HasOne("SPASMART.Models.VaiTro", "VaiTro")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("SPASMART.Models.ThanhToan", b =>
                {
                    b.HasOne("SPASMART.Models.HoaDon", "HoaDon")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("SPASMART.Models.Voucher", b =>
                {
                    b.HasOne("SPASMART.Models.KhachHang", "KhachHang")
                        .WithMany("Vouchers")
                        .HasForeignKey("MaKhachHang");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("SPASMART.Models.DichVu", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("LichHens");
                });

            modelBuilder.Entity("SPASMART.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("SPASMART.Models.KhachHang", b =>
                {
                    b.Navigation("LichHens");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("SPASMART.Models.LichHen", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("SPASMART.Models.NhanVien", b =>
                {
                    b.Navigation("LichHens");

                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("SPASMART.Models.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("SPASMART.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("SPASMART.Models.TaiKhoan", b =>
                {
                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("SPASMART.Models.VaiTro", b =>
                {
                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("SPASMART.Models.Voucher", b =>
                {
                    b.Navigation("HoaDon");
                });
#pragma warning restore 612, 618
        }
    }
}
